# Build binary.
FROM golang:1.16.0-alpine3.13 AS build-env
RUN apk add --update --no-cache git
COPY . /go/src/github.com/alex-ant/ports
WORKDIR /go/src/github.com/alex-ant/ports/cmd/client
RUN go build -o dist/goapp

# Build image.
FROM alpine:3.13
RUN  apk update && apk upgrade \
    && apk add --no-cache ca-certificates \
    && update-ca-certificates
WORKDIR /app
COPY --from=build-env /go/src/github.com/alex-ant/ports/cmd/client/dist/goapp /app/
COPY --from=build-env /go/src/github.com/alex-ant/ports/ports.json /app/
ENTRYPOINT ./goapp
