# Build binary.
FROM golang:1.16.0-alpine3.13 AS build-env
RUN apk add --update --no-cache git
RUN go get -u github.com/gobuffalo/packr/packr
COPY . /go/src/github.com/alex-ant/ports
WORKDIR /go/src/github.com/alex-ant/ports/cmd/server
RUN packr build -o dist/goapp

# Build image.
FROM alpine:3.13
RUN  apk update && apk upgrade \
    && apk add --no-cache ca-certificates \
    && update-ca-certificates
WORKDIR /app
COPY --from=build-env /go/src/github.com/alex-ant/ports/cmd/server/dist/goapp /app/
ENTRYPOINT ./goapp
